# Generated by Django 2.2.3 on 2019-08-22 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('location', models.CharField(max_length=255, verbose_name='Адрес')),
                ('birth_date', models.DateField(blank=True, default='', verbose_name='Дата рождения')),
                ('role', models.PositiveSmallIntegerField(choices=[(0, 'Незарегистрирован'), (1, 'Заказчик'), (2, 'Закупщик'), (3, 'Администратор')], default=0, verbose_name='Роль')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Неоплачен'), (1, 'Оплата в процессе подтверждения'), (2, 'Оплата подтверждена'), (3, 'В обработке'), (4, 'Готов к выдаче'), (5, 'Закрыт')], default=0)),
                ('paid_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('actual_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_order_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_order_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_date',),
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('vk_link', models.CharField(max_length=256)),
                ('place', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('picture', models.CharField(max_length=256)),
                ('product_type', models.CharField(blank=True, default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('image', models.ImageField(upload_to=main.models.get_path_to_product_image, verbose_name='Фото товара')),
                ('place', models.CharField(default='', max_length=150, verbose_name='Место')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('comment', models.CharField(default='', max_length=255, verbose_name='Комментарий к товару')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('shopping_type', models.PositiveSmallIntegerField(choices=[(0, 'Индивидуальная покупка'), (1, ' Совместная покупка')], default=0, verbose_name='Вид закупки')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_product_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_product_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order_comment', models.TextField(blank=True, default='', max_length=255, verbose_name='Комментарий к заказу')),
                ('customer_comment', models.TextField(blank=True, default='', max_length=255, verbose_name='Комментарий заказчика')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Создан'), (1, 'Выкуплен'), (2, 'Не выкуплен')], default=0, verbose_name='Статус')),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Не активный'), (1, 'Активный'), (2, 'Используется')], default=2, verbose_name='Состояние')),
                ('delivery', models.PositiveSmallIntegerField(choices=[(0, 'Закупка вместе с доставкой'), (1, 'Только доставка')], default=0, verbose_name='Тип доставки')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_orderitem_created_by', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Order', verbose_name='Заказ')),
                ('parent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.OrderItem', verbose_name='Заменяемый товар')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Product', verbose_name='Продукт')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_orderitem_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
