# Generated by Django 2.2.2 on 2019-07-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.PositiveIntegerField(choices=[(0, 'Zakazschik'), (1, 'Sborchik'), (2, 'Zakupchik'), (3, 'Administrator')], default=0),
        ),
    ]
