# Generated by Django 2.2.3 on 2019-08-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Неоплачен'), (1, 'Оплата в процессе подтверждения'), (2, 'Оплата подтверждена'), (3, 'В обработке'), (4, 'Готов к выдаче'), (5, 'Закрыт')], default=0),
        ),
    ]
