# Generated by Django 2.2.3 on 2019-08-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingOption',
            fields=[
                ('s_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('s_value', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('role',)},
        ),
    ]
