# Generated by Django 2.2.3 on 2019-11-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_update_for_replacement__no_deleting'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
