# Generated by Django 2.2.3 on 2019-09-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190828_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Самовывоз'), (1, 'Хранение'), (2, 'Почта'), (3, 'Доставка на дом'), (4, 'Транспортная компания')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Адрес доставки'),
        ),
    ]
