# Generated by Django 2.2.2 on 2019-07-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveIntegerField(choices=[(0, 'Заказчик'), (1, 'Сборщик'), (2, 'Закупщик'), (3, 'Администратор')], default=0),
        ),
    ]
