# Generated by Django 2.2.3 on 2019-08-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190805_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
