# Generated by Django 2.2.2 on 2019-07-07 18:25

from django.db import migrations, models
import main.core.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190703_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('place', models.CharField(blank=True, max_length=150, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_comment', models.TextField(blank=True, max_length=255, null=True)),
                ('customer_comment', models.TextField(blank=True, max_length=255, null=True)),
            ],
            bases=(main.core.mixins.WithTimestampMixin, main.core.mixins.WithUserMixin, models.Model),
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='space',
            new_name='place',
        ),
    ]
