# Generated by Django 2.2.3 on 2019-08-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_paid_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='place',
        ),
        migrations.AddField(
            model_name='product',
            name='place',
            field=models.CharField(default='', max_length=150),
        ),
    ]
