# Generated by Django 2.2.3 on 2019-09-04 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_receipt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location',
            new_name='delivery_address',
        ),
    ]
