# Generated by Django 2.2.3 on 2019-08-07 07:23

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190806_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='comment',
            field=models.CharField(default='', max_length=255, verbose_name='Комментарий к товару'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=main.models.get_path_to_product_image, verbose_name='Фото товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='place',
            field=models.CharField(default='', max_length=150, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shopping_type',
            field=models.PositiveIntegerField(choices=[(0, 'Индивидуальная покупка'), (1, ' Совместная покупка')], default=0, verbose_name='Вид закупки'),
        ),
    ]
