# Generated by Django 2.2.2 on 2019-07-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190707_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cost',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Создан'), (1, 'Оплачен'), (2, 'Закрыт')], default=0),
        ),
    ]
