# Generated by Django 2.2.3 on 2019-08-11 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190807_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='active',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='active',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.OrderItem', verbose_name='Заменяемый товар'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Не активный'), (1, 'Активный'), (2, 'Используется')], default=2, verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Неоплачен'), (1, 'Оплата в процессе подтверждения'), (2, 'Оплата подтверждена'), (3, 'В обработке'), (4, 'Готов к выдаче'), (5, 'Закрыт')], default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='customer_comment',
            field=models.TextField(blank=True, default='', max_length=255, verbose_name='Комментарий заказчика'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_comment',
            field=models.TextField(blank=True, default='', max_length=255, verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Создан'), (1, 'Выкуплен'), (2, 'Не выкуплен')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shopping_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Индивидуальная покупка'), (1, ' Совместная покупка')], default=0, verbose_name='Вид закупки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Незарегистрирован'), (1, 'Заказчик'), (2, 'Закупщик'), (3, 'Администратор')], default=0, verbose_name='Роль'),
        ),
    ]
