# Generated by Django 2.2.3 on 2019-09-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190904_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingoption',
            name='contacts',
            field=models.TextField(blank=True, default='', max_length=255, verbose_name='Контакты'),
        ),
        migrations.AddField(
            model_name='settingoption',
            name='partnership',
            field=models.TextField(blank=True, default='', max_length=255, verbose_name='Сотрудничество'),
        ),
    ]
