# Generated by Django 2.2.3 on 2019-08-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190811_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
