# Generated by Django 2.2.3 on 2019-09-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190927_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, null=True)),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.AlterField(
            model_name='provider',
            name='place',
            field=models.CharField(default='', max_length=150, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='settingoption',
            name='partnership',
            field=models.TextField(blank=True, default='', max_length=1024, verbose_name='Сотрудничество'),
        ),
    ]
