# Generated by Django 2.2.3 on 2019-07-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190718_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveIntegerField(choices=[(0, 'Незарегистрирован'), (1, 'Заказчик'), (2, 'Закупщик'), (3, 'Администратор')], default=0),
        ),
    ]
