# Generated by Django 2.2.3 on 2019-10-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190930_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='delivery',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Закупка вместе с процентом'), (1, 'Только процент')], default=0, verbose_name='Тип доставки'),
        ),
    ]
