# Generated by Django 2.2.3 on 2019-08-20 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_price_from_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivery',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Закупка вместе с доставкой'), (1, 'Только доставка')], default=0, verbose_name='Тип доставки'),
        ),
    ]
