# Generated by Django 2.2.3 on 2019-07-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190722_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Создан'), (1, 'Оплачен'), (2, 'В обработке'), (3, 'Готов к выдаче'), (4, 'Закрыт')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveIntegerField(choices=[(0, 'Незарегистрирован'), (1, 'Заказчик'), (2, 'Закупщик'), (3, 'Администратор')], default=0, verbose_name='Роль'),
        ),
    ]
