# Generated by Django 2.2.3 on 2019-10-11 06:33

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_fields_from_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingOptionImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.models.get_path_to_setting_images)),
            ],
        ),
    ]
